server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://12.1.1.31:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver